### ISSUE TITLE
parseInput and prepareInput functions are too large and contain repeating code

### ISSUE THREAD

**Issue by dpalii** [andriikovall/euro-diff#2]
I propose to move some of the code in parseInput function, as it is too large and contains repeating code. For example, code for parsing x and y coordinates is very similar and could be moved to a function. Code for reading the amount of countries could also be moved to a new function to make the parseInput function smaller and easier to read.

**Comment by dpalii** [comment]
Function prepareInput also seems too large for me and I think that it's size can be easily reduced.

**Comment by andriikovall** [comment]
will be resolved by #4
