### ISSUE TITLE
sendCoinsToNeighbors logic question

### ISSUE THREAD

**Issue by dpalii** [andriikovall/euro-diff#3]
I noticed in sendCoinsToNeighbors that coins that are given to each neighbor are added to the neighbor cities as coinsToReceive, but in the current city they are immidiately subtracted from coins. It seems to me that this is not exactly correct, as all the calculations should be based on the amount of coins that was available at the start of the day.

**Comment by andriikovall** [comment]
Good comment on that, thanks. Take a look at the pr

**Comment by dpalii** [comment]
Issue resolved now, thanks
