### ISSUE TITLE
starting days from -1

### ISSUE THREAD

**Issue by IanaKhitsko** [andriikovall/euro-diff#8]
https://github.com/andriikovall/euro-diff/blob/f5eb290c494cf1a18ec1c6945f119c121b9c76b8/src/lib/euroDiffusion/euroDiffusion.ts#L19

I just wonder, why did you start here not from 0?

**Comment by andriikovall** [comment]
It's a common practice to return `-1` as a kind of **error** result. `0` may be treated as a result of the computing but may signal the mistake. 

I understand `> 0` as a result and `-1` as a default **negative/false/not-started** value.

take JS `array.findIndex` as an example. It's about alightly different thing but I believe you have got my point
